### ISSUE TITLE
Scene

### ISSUE THREAD

**Issue by kinhosz** [kinhosz/Appel#5]
A Scene has lights, color filter and objects.

## Basic fields
- [ ] `Lights`
- [ ] `Environment` (just a color)
- [ ] `Objects` on scene

## Basic Methods
- [ ] intersect

**Comment by mateuseap** [comment]
Vou dale nessa, quando ao menos um `Object` (`Sphere`, `Plane`, etc) for para main

**Comment by mateuseap** [comment]
Vou dale nessa
