### ISSUE TITLE
Object

### ISSUE THREAD

**Issue by kinhosz** [kinhosz/Appel#7]
To simplify and avoid errors with `C++ object typename`, let's call an Object as `box`.

A box can be anything with:
* color
* can be storaged inside a world real box.
* mass

## Basic fields

- [ ] Diffuse coefficient
- [ ] Specular coefficient
- [ ] Ambient coefficient
- [ ] Reflection coefficient
- [ ] Transmission coefficient
- [ ] Roughness coefficient

## Basic methods

> empty at the moment...

**Comment by mateuseap** [comment]
Vou puxar esse
